const courses = [
  {
    id: "1",
    slug: "python-django-web-apps",
    title: "Build Web Applications with Python and Django",
    subtitle: "Learn to design, build, and deploy production-ready web apps from scratch.",
    category: "Web Development",
    level: "Intermediate",
    price: 49,
    originalPrice: 99,
    rating: 4.8,
    reviews: 2140,
    students: 18420,
    duration: "32h 15m",
    lectures: 128,
    language: "English",
    lastUpdated: "September 2026",
    image:
      "https://images.unsplash.com/photo-1517694710533-d299ea62b273?w=900&h=560&fit=crop",
    instructor: {
      name: "Ava Martinez",
      title: "Senior Full-Stack Engineer",
      avatar: "/images/Image (1).png",
      bio: "Ava has spent 10+ years building products at high-growth startups. She teaches practical Django with a focus on real-world architecture, testing, and shipping.",
      courses: 12,
      students: 84200,
      rating: 4.9,
    },
    overview:
      "This course takes you from Python basics to a complete Django application. You will model data, build REST-style views, handle authentication, and deploy with confidence. Every module ends with a project checkpoint so you leave with a portfolio-ready app.",
    learn: [
      "Design Django models, views, and templates the right way",
      "Implement user authentication, permissions, and profiles",
      "Build forms, validation, and CRUD workflows",
      "Connect PostgreSQL and structure production settings",
      "Add dashboards, search, and file uploads",
      "Deploy your application and monitor it after launch",
    ],
    includes: [
      "32 hours on-demand video",
      "18 downloadable resources",
      "Full lifetime access",
      "Access on mobile and TV",
      "Certificate of completion",
    ],
    curriculum: [
      {
        title: "Getting started",
        lectures: 8,
        duration: "1h 20m",
        lessons: [
          { title: "Welcome and course roadmap", duration: "08:12", preview: true },
          { title: "How to set up your environment", duration: "12:40", preview: true },
          { title: "Python refresh for Django", duration: "18:05", preview: false },
        ],
      },
      {
        title: "Django fundamentals",
        lectures: 16,
        duration: "4h 10m",
        lessons: [
          { title: "Projects, apps, and settings", duration: "14:22", preview: false },
          { title: "URLs, views, and templates", duration: "21:08", preview: false },
          { title: "The request / response cycle", duration: "16:44", preview: false },
        ],
      },
      {
        title: "Models and the admin",
        lectures: 14,
        duration: "3h 45m",
        lessons: [
          { title: "Designing your data model", duration: "19:30", preview: false },
          { title: "Migrations in practice", duration: "11:18", preview: false },
          { title: "Customizing Django admin", duration: "15:52", preview: false },
        ],
      },
      {
        title: "Auth, dashboards, and deploy",
        lectures: 22,
        duration: "6h 05m",
        lessons: [
          { title: "Signup, login, and sessions", duration: "17:40", preview: false },
          { title: "Building the student dashboard", duration: "24:16", preview: false },
          { title: "Deploying to production", duration: "20:09", preview: false },
        ],
      },
    ],
  },
  {
    id: "2",
    slug: "ui-ux-design-masterclass",
    title: "Build Digital Asset: A Comprehensive Guide",
    subtitle: "Unlock the Power of Digital Creation with Expert Guidance",
    category: "Design",
    level: "Intermediate",
    price: 25,
    originalPrice: 79,
    rating: 4.8,
    reviews: 172,
    students: 199,
    duration: "24 hours",
    lectures: 112,
    language: "English",
    lastUpdated: "August 2026",
    image: "/images/Frame (1).png",
    instructor: {
      name: "PurePearl Studio",
      title: "Professional Creator",
      avatar: "/images/Ellipse (6).png",
      bio: "Emily designs learning products used by millions. She coaches teams on research, systems thinking, and shipping delightful interfaces.",
      courses: 8,
      students: 41200,
      rating: 4.8,
    },
    overview:
      "Embark on an enlightening exploration into the world of digital creation with our comprehensive course, \"Build Digital Assets: A Comprehensive Guide.\" This transformative learning experience invites you to delve deep into the intricacies of crafting impactful digital content. From laying the groundwork with foundational concepts to mastering advanced techniques, this guide is meticulously curated to empower you with the skills essential for navigating the dynamic landscape of digital asset creation.\n\nIn the initial modules, you'll establish a solid foundation by immersing yourself in the foundational concepts that form the backbone of digital asset creation. Understand the fundamental elements that constitute compelling digital content and gain proficiency in leveraging these elements to communicate effectively in the digital realm.\n\nAs you progress through the course, you'll ascend to higher levels of expertise, delving into the nuances of design principles that drive impactful creations. Uncover the secrets behind effective visual communication, exploring color theory, typography, and layout strategies that elevate your digital assets to new heights. Engage in hands-on exercises that reinforce your understanding, allowing you to apply these principles in practical scenarios.",
    learn: [
      "Run user interviews and turn insights into problems",
      "Map user journeys and information architecture",
      "Wireframe quickly and iterate with feedback",
      "Build a scalable UI kit in Figma",
      "Prototype interactions and microcopy",
      "Prepare developer-ready design specs",
    ],
    includes: [
      "38 hours on-demand video",
      "Figma source files",
      "Full lifetime access",
      "Community critique sessions",
      "Certificate of completion",
    ],
    curriculum: [
      {
        title: "Design foundations",
        lectures: 10,
        duration: "2h 40m",
        lessons: [
          { title: "Introduction to Digital Assets", duration: "12 mins", preview: true },
          { title: "Design Principles for Impacts", duration: "21 mins", preview: true },
          { title: "Advanced Techniques in Digital Creation", duration: "16 mins", preview: false },
        ],
      },
      {
        title: "Research and flows",
        lectures: 12,
        duration: "3h 15m",
        lessons: [
          { title: "Interview scripts that work", duration: "16:40", preview: false },
          { title: "Journey maps and opportunity areas", duration: "18:05", preview: false },
        ],
      },
    ],
  },
  {
    id: "3",
    slug: "complete-web-development-bootcamp",
    title: "Complete Web Development Bootcamp",
    subtitle: "HTML, CSS, JavaScript, React, and Node — one complete path.",
    category: "Web Development",
    level: "Beginner",
    price: 49,
    originalPrice: 99,
    rating: 4.8,
    reviews: 2450,
    students: 12500,
    duration: "42h",
    lectures: 164,
    language: "English",
    lastUpdated: "July 2026",
    image:
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=900&h=560&fit=crop",
    instructor: {
      name: "John Smith",
      title: "Lead Web Instructor",
      avatar:
        "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop",
      bio: "John has taught 50,000+ students how to ship websites. His teaching style is friendly, project-based, and career focused.",
      courses: 15,
      students: 120400,
      rating: 4.8,
    },
    overview:
      "A practical bootcamp covering frontend and backend fundamentals. Build real projects every week and finish with a full-stack portfolio.",
    learn: [
      "Build responsive layouts with modern CSS",
      "Write clean JavaScript for the browser",
      "Create interactive UIs with React",
      "Build APIs with Node and Express",
      "Store data and handle authentication",
      "Deploy your projects to the web",
    ],
    includes: [
      "42 hours on-demand video",
      "Coding exercises",
      "Full lifetime access",
      "Career worksheets",
      "Certificate of completion",
    ],
    curriculum: [
      {
        title: "HTML & CSS",
        lectures: 20,
        duration: "5h 10m",
        lessons: [
          { title: "Semantic HTML in 2026", duration: "12:00", preview: true },
          { title: "Flexbox and Grid layouts", duration: "22:18", preview: false },
        ],
      },
      {
        title: "JavaScript",
        lectures: 24,
        duration: "6h 40m",
        lessons: [
          { title: "Functions, arrays, and objects", duration: "19:44", preview: false },
          { title: "DOM projects", duration: "25:02", preview: false },
        ],
      },
    ],
  },
  {
    id: "4",
    slug: "data-science-machine-learning",
    title: "Data Science & Machine Learning A-Z",
    subtitle: "Python, pandas, visualization, and applied ML models.",
    category: "Data Science",
    level: "Intermediate",
    price: 59,
    originalPrice: 119,
    rating: 4.9,
    reviews: 1820,
    students: 9800,
    duration: "56h",
    lectures: 188,
    language: "English",
    lastUpdated: "June 2026",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&h=560&fit=crop",
    instructor: {
      name: "Sarah Johnson",
      title: "Data Scientist",
      avatar:
        "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop",
      bio: "Sarah leads applied ML teams and loves turning messy datasets into stories leaders can act on.",
      courses: 9,
      students: 67300,
      rating: 4.9,
    },
    overview:
      "Go from spreadsheets to machine learning. You will clean data, visualize insights, and train models you can explain to non-technical stakeholders.",
    learn: [
      "Use pandas to wrangle real datasets",
      "Visualize insights that drive decisions",
      "Train and evaluate classic ML models",
      "Avoid leakage and overfit",
      "Present findings with notebooks and slides",
      "Ship a capstone analysis",
    ],
    includes: [
      "56 hours on-demand video",
      "Notebook templates",
      "Full lifetime access",
      "Capstone dataset",
      "Certificate of completion",
    ],
    curriculum: [
      {
        title: "Python for data",
        lectures: 14,
        duration: "3h 50m",
        lessons: [
          { title: "Notebooks and environments", duration: "10:18", preview: true },
          { title: "pandas essentials", duration: "21:40", preview: false },
        ],
      },
    ],
  },
  {
    id: "5",
    slug: "advanced-react-nextjs",
    title: "Advanced React & Next.js Development",
    subtitle: "App Router, server components, and production patterns.",
    category: "Web Development",
    level: "Advanced",
    price: 54,
    originalPrice: 109,
    rating: 4.9,
    reviews: 980,
    students: 5200,
    duration: "48h",
    lectures: 142,
    language: "English",
    lastUpdated: "September 2026",
    image:
      "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=900&h=560&fit=crop",
    instructor: {
      name: "Mike Wilson",
      title: "Staff Frontend Engineer",
      avatar:
        "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
      bio: "Mike builds large React platforms and teaches the patterns that keep teams fast as codebases grow.",
      courses: 6,
      students: 28900,
      rating: 4.9,
    },
    overview:
      "Level up from basic React to a production Next.js app: routing, data fetching, caching, auth, and performance.",
    learn: [
      "Structure App Router projects",
      "Choose client vs server components",
      "Fetch and cache data correctly",
      "Handle auth and protected routes",
      "Optimize images, fonts, and bundles",
      "Test and deploy with confidence",
    ],
    includes: [
      "48 hours on-demand video",
      "Starter repos",
      "Full lifetime access",
      "Code reviews checklist",
      "Certificate of completion",
    ],
    curriculum: [
      {
        title: "Next.js architecture",
        lectures: 12,
        duration: "3h 20m",
        lessons: [
          { title: "App Router mental model", duration: "14:55", preview: true },
          { title: "Layouts and templates", duration: "12:30", preview: false },
        ],
      },
    ],
  },
  {
    id: "6",
    slug: "digital-marketing-growth",
    title: "Digital Marketing & Growth Fundamentals",
    subtitle: "Content, SEO, paid ads, and analytics for creators.",
    category: "Marketing",
    level: "Beginner",
    price: 29,
    originalPrice: 69,
    rating: 4.6,
    reviews: 760,
    students: 4300,
    duration: "22h",
    lectures: 74,
    language: "English",
    lastUpdated: "May 2026",
    image:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&h=560&fit=crop",
    instructor: {
      name: "Noah Patel",
      title: "Growth Lead",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
      bio: "Noah has scaled education products from zero to millions of visits using simple, repeatable growth loops.",
      courses: 4,
      students: 19800,
      rating: 4.6,
    },
    overview:
      "Learn a practical growth stack: positioning, content, SEO, campaigns, and measurement. Built for course creators and small teams.",
    learn: [
      "Clarify your offer and audience",
      "Plan a content engine",
      "Run basic SEO and landing pages",
      "Launch paid experiments safely",
      "Read analytics without overwhelm",
      "Build a weekly growth cadence",
    ],
    includes: [
      "22 hours on-demand video",
      "Campaign templates",
      "Full lifetime access",
      "Worksheet pack",
      "Certificate of completion",
    ],
    curriculum: [
      {
        title: "Positioning",
        lectures: 8,
        duration: "1h 50m",
        lessons: [
          { title: "Who is this for?", duration: "09:40", preview: true },
          { title: "Offer design", duration: "13:12", preview: false },
        ],
      },
    ],
  },
  {
    id: "7",
    slug: "mobile-apps-with-flutter",
    title: "Mobile Apps with Flutter",
    subtitle: "Ship iOS and Android apps from a single codebase.",
    category: "Mobile",
    level: "Intermediate",
    price: 44,
    originalPrice: 89,
    rating: 4.7,
    reviews: 610,
    students: 3100,
    duration: "36h",
    lectures: 110,
    language: "English",
    lastUpdated: "April 2026",
    image:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=900&h=560&fit=crop",
    instructor: {
      name: "Lina Park",
      title: "Mobile Engineer",
      avatar:
        "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop",
      bio: "Lina ships consumer mobile apps and teaches Flutter with a strong eye for polish and performance.",
      courses: 5,
      students: 22100,
      rating: 4.7,
    },
    overview:
      "Build beautiful Flutter apps: widgets, state, navigation, APIs, and store submission basics.",
    learn: [
      "Compose Flutter layouts",
      "Manage state cleanly",
      "Talk to REST APIs",
      "Persist local data",
      "Add auth and profiles",
      "Prepare a store release",
    ],
    includes: [
      "36 hours on-demand video",
      "Starter app",
      "Full lifetime access",
      "Design assets",
      "Certificate of completion",
    ],
    curriculum: [
      {
        title: "Flutter basics",
        lectures: 12,
        duration: "2h 55m",
        lessons: [
          { title: "Widgets and composition", duration: "15:20", preview: true },
          { title: "Theming your app", duration: "11:08", preview: false },
        ],
      },
    ],
  },
  {
    id: "8",
    slug: "cloud-fundamentals-aws",
    title: "Cloud Fundamentals with AWS",
    subtitle: "Core services, architecture, and a deployable project.",
    category: "Cloud",
    level: "Beginner",
    price: 45,
    originalPrice: 90,
    rating: 4.5,
    reviews: 540,
    students: 2800,
    duration: "28h",
    lectures: 88,
    language: "English",
    lastUpdated: "March 2026",
    image:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=900&h=560&fit=crop",
    instructor: {
      name: "Chris Adeyemi",
      title: "Cloud Architect",
      avatar:
        "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop",
      bio: "Chris helps teams move to the cloud without drowning in services. Expect diagrams, labs, and clear trade-offs.",
      courses: 7,
      students: 30500,
      rating: 4.5,
    },
    overview:
      "Learn the AWS building blocks you will actually use: compute, storage, networking, IAM, and a simple production deploy.",
    learn: [
      "Navigate the AWS console with intent",
      "Use IAM the least-privilege way",
      "Deploy compute and storage",
      "Design a simple 3-tier app",
      "Watch costs and logs",
      "Ship a capstone architecture",
    ],
    includes: [
      "28 hours on-demand video",
      "Architecture diagrams",
      "Full lifetime access",
      "Lab checklist",
      "Certificate of completion",
    ],
    curriculum: [
      {
        title: "Cloud mental models",
        lectures: 9,
        duration: "2h 10m",
        lessons: [
          { title: "Regions, accounts, and IAM", duration: "13:40", preview: true },
          { title: "Choosing compute", duration: "16:22", preview: false },
        ],
      },
    ],
  },
  {
    id: "9",
    slug: "cybersecurity-essentials",
    title: "Cybersecurity Essentials for Developers",
    subtitle: "Threats, secure coding, and practical defense for web teams.",
    category: "Cybersecurity",
    level: "Beginner",
    price: 42,
    originalPrice: 84,
    rating: 4.6,
    reviews: 430,
    students: 2100,
    duration: "24h",
    lectures: 72,
    language: "English",
    lastUpdated: "February 2026",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=900&h=560&fit=crop",
    instructor: {
      name: "Priya Nair",
      title: "Security Engineer",
      avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop",
      bio: "Priya has led security reviews at fintech companies and teaches developers how to ship safer software without slowing down.",
      courses: 3,
      students: 12400,
      rating: 4.6,
    },
    overview: "A practical security course for builders: OWASP risks, auth pitfalls, secrets, and a checklist you can use on every sprint.",
    learn: ["Spot common web vulnerabilities", "Harden authentication flows", "Handle secrets and keys", "Review pull requests for security", "Respond to incidents calmly", "Build a personal security checklist"],
    includes: ["24 hours on-demand video", "Checklists", "Full lifetime access", "Lab walkthroughs", "Certificate of completion"],
    curriculum: [{ title: "Threats and mindset", lectures: 8, duration: "1h 40m", lessons: [{ title: "How attackers think", duration: "12:10", preview: true }, { title: "OWASP overview", duration: "14:22", preview: false }] }],
  },
  {
    id: "10",
    slug: "ai-prompt-engineering",
    title: "AI & Prompt Engineering for Creators",
    subtitle: "Use AI tools to research, draft, and ship learning content faster.",
    category: "AI & Machine Learning",
    level: "Beginner",
    price: 35,
    originalPrice: 70,
    rating: 4.7,
    reviews: 890,
    students: 6400,
    duration: "16h",
    lectures: 54,
    language: "English",
    lastUpdated: "September 2026",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=900&h=560&fit=crop",
    instructor: {
      name: "Jordan Blake",
      title: "AI Educator",
      avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop",
      bio: "Jordan helps educators use AI as a copilot — not a replacement — with clear workflows and quality bars.",
      courses: 4,
      students: 27600,
      rating: 4.7,
    },
    overview: "Learn prompt patterns, evaluation, and ethical use so you can create better courses and docs with AI assistance.",
    learn: ["Write prompts that stay on brief", "Evaluate AI output quality", "Build repeatable content workflows", "Keep a human quality bar", "Avoid common AI pitfalls", "Ship a content system"],
    includes: ["16 hours on-demand video", "Prompt library", "Full lifetime access", "Templates", "Certificate of completion"],
    curriculum: [{ title: "Prompt patterns", lectures: 7, duration: "1h 25m", lessons: [{ title: "Briefs vs prompts", duration: "09:50", preview: true }, { title: "Iteration loops", duration: "11:30", preview: false }] }],
  },
  {
    id: "11",
    slug: "figma-to-tailwind",
    title: "From Figma to Tailwind CSS",
    subtitle: "Turn high-fidelity designs into production-ready pages.",
    category: "Design",
    level: "Intermediate",
    price: 38,
    originalPrice: 76,
    rating: 4.8,
    reviews: 720,
    students: 3900,
    duration: "20h",
    lectures: 68,
    language: "English",
    lastUpdated: "August 2026",
    image: "https://images.unsplash.com/photo-1586717791821-3f44a563c4bb?w=900&h=560&fit=crop",
    instructor: {
      name: "Emily Chen",
      title: "Product Designer",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop",
      bio: "Emily designs learning products used by millions. She coaches teams on research, systems thinking, and shipping delightful interfaces.",
      courses: 8,
      students: 41200,
      rating: 4.8,
    },
    overview: "Translate spacing, type, and components from Figma into Tailwind without losing the design intent.",
    learn: ["Read Figma specs quickly", "Map tokens to Tailwind", "Build reusable UI pieces", "Handle responsive breakpoints", "Polish hover and motion", "Hand off with confidence"],
    includes: ["20 hours on-demand video", "Figma file", "Full lifetime access", "Component kit", "Certificate of completion"],
    curriculum: [{ title: "Tokens and type", lectures: 6, duration: "1h 18m", lessons: [{ title: "Spacing systems", duration: "10:40", preview: true }, { title: "Type scale", duration: "12:05", preview: false }] }],
  },
  {
    id: "12",
    slug: "sql-for-analysts",
    title: "SQL for Analysts",
    subtitle: "Query real datasets and answer business questions with SQL.",
    category: "Data Science",
    level: "Beginner",
    price: 32,
    originalPrice: 64,
    rating: 4.8,
    reviews: 1100,
    students: 8700,
    duration: "18h",
    lectures: 60,
    language: "English",
    lastUpdated: "July 2026",
    image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=900&h=560&fit=crop",
    instructor: {
      name: "Sarah Johnson",
      title: "Data Scientist",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop",
      bio: "Sarah leads applied ML teams and loves turning messy datasets into stories leaders can act on.",
      courses: 9,
      students: 67300,
      rating: 4.9,
    },
    overview: "From SELECT to window functions. You will practice on realistic tables and leave with a query notebook you can reuse at work.",
    learn: ["Write clean SELECT queries", "Join tables confidently", "Aggregate and group", "Use window functions", "Spot bad data", "Present query results"],
    includes: ["18 hours on-demand video", "Practice database", "Full lifetime access", "Cheat sheet", "Certificate of completion"],
    curriculum: [{ title: "Query foundations", lectures: 9, duration: "2h 05m", lessons: [{ title: "SELECT and WHERE", duration: "13:10", preview: true }, { title: "JOINs that make sense", duration: "16:40", preview: false }] }],
  },
];

module.exports = { courses };
